image: condaforge/mambaforge:latest

tasks:
  - init: |
      conda create -n ChatDev_conda_env python=3.9 -y
      conda activate ChatDev_conda_env
      pip3 install -r requirements.txt
      export OPENAI_API_KEY=$OPENAI_API_KEY_TESTING


